# generic gpio support: platform drivers, dedicated expander chips, etc


obj-$(CONFIG_GPIO_DB_OUT)      += gpio_db_out.o
obj-$(CONFIG_GPIO_DB_IN)      += gpio_db_in.o
obj-$(CONFIG_GPIO_DB_INT)      += gpio_gps_interrupt.o
obj-$(CONFIG_GPIO_DB_INT)      += gpio_rtc_interrupt.o

